language: node_js
cache:
  directories:
    - node_modules
    - '~/.npm'
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  slack:
    secure: 'rtDhCK5xxLW5cIa79orr+TOO84m2+hgAK+9OqwYSzVah1It+7L7aPLYWoHooRteQSxRY6FKefGM3NCnBy/REnbrsipWhTyFbqjjJ2cghyOs1gs+giJpSD8TvXEz/4EOM/riMDFWuyxH+3jW9Rkryozu7e7wbEig7zNVhMlKrgyZxIuxII/4vLrD1vLHY3LYHv0J0v8uivGJCSpDMaYJIUberEJG7WAcpK/Ni56QUsvCmJkm/4uYFDDXQjWCs269UJLBzw4Pbtfgz39obSP25rTfjayle2yEbUdhSdauPjW5pdlPqpULoQ1BFxOQWGoIB1DMxq6wCLJuWvW/MhgAf2ZFh/fm4ovFHBJlb4bAi8JMfuatU72qihJSR35iSDPxNBr7EPbKWWqTxDM+7zHPR7KYuzG7HAm6jvFN8tuVQ7+molElOWcspsRUSd3Ml/dPoNABctbXBnfE7GUCmITzoWV0FGTIU5oQJZk9FcKKQUDR8X0h7d0s5fEmm+JUMXgXzSU9emBWaSPQEodMjCpI7o0wH3EvCMBX9vtKs2UXwV569Hw0rYY+KKHzlHpQYxJarPtgDxVGj6NMr6udVYT75wAwJSI6msQ8aQ3nsrBNxDrVrIzrLaolu8/Q71gFXbWFW+lOS4Yq7VYomSvZM18T+ruEx8TkL5Xwk4c2qlX1biPg='
  email:
    recipients:
      - ala1289@gmail.com
      - hector.olvera@ciencias.unam.mx
    on_success: always
    on_failure: always
deploy:
  provide: heroku
  skip_cleanup: true
  keep_history: true
  api_key:
    secure: janaHeBOPTE1WfO+njngGIEsrRG5VK9q7biHMA+v5pZ8Dw0BluzdjCIGLm9ukE/JogHc2lVTbxmH2gffmSrYJNanYJycEVOqCCIi/NU8kss0eW495tclMaJorieaBfwfGMui2lE73A0MOsOqY+skRhJhWoaJN6XhqGhgFnA0goUJG8dB87ZCasHX33X36NXT7jhvKSpHP21Wxa1oPhBJuthTr4S6NG5WBXowiXRT7akv5kHDGWE4ZjFHA+Ggjw47nEciN9hQfI/L7ysM/u8s6j1CO2yjl03wUDqe7d80Yd05UL+Inhnnkj/YChIsX193DptzPn5ee8eU808eHPMzRPECF99XMZ+q7xkf+hmj/+XwEG9/HAyTv0iStur97o17/TnhZaMfiHEGdR5QlsMqyGfZKp/z6oMlcaVIs8RpHE3NSNwJEYltdeqkthBP3+1j20qlYPaq41K8OS4hukBIMFhFzvTT360S/Fqn9CWUMlhZ9VjvUcsgzBt6mbWgkM59djRtmWuZlJCbDODt2BuuXCaoQgXcrEZRG9gs+tNg6Eo+f+KpS+4sx0jogI+Vvy8vJru09/tG/IgPBkYN7FBNZvfcPM+CTpxTyvdelnI2V0aPeYEcyoXGXrUx2sZebRCEhcOidqWx5GgRtwI32wjKtFGo+d/EynNv4VuOyEDa4tI=
  app: backendhalah
  on:
    repo: hyfi06/platzi-master-end-game-backend
